### ISSUE TITLE
Toggle on/off option?

### ISSUE THREAD

**Issue by tresrottn** [tomroyal/Make-America-Kittens-Again#6]
Hi Tom!

LOVE the extension. It's simply wonderful. I encountered a new thing today, and it prompted this request.
I was making an anti-trump meme, using skeptical African kid, and it did have trumps name on it, but it kittened on me. 
I actually had to remove the extension in order to see the image and be able to save it to my computer. I've had to remove the extension a couple of times due to its vigorous kittening (lol, which is NOT a bad thing, I like its tenacity!) then go back and readd it.
Is there a way to add a toggle off /on for the extension for the times that we want to see the image being displayed? That way, we won't have to remove it. I plan on it being on my browser for at least 4 more years, ROFL.
Thanks!

**Comment by dcwarwick** [comment]
I second this --- I like having kittens instead of Trump, but occasionally there is a picture I really want to see because a discussion is talking about it, and it's a shame to have to disable the whole extension just to do that and then re-enable it afterwards.

One simple way to provide this would be to include Trump as one of the checkbox options, and simply have it pre-checked.

**Comment by tomroyal** [comment]
Hi,

My current plan for this is a "disable for this page" option, available via the page context menu in Chrome. That way if there's a page where you want to view the original, that's just a click away.

The code for this is currently in the "contextmenu" branch if you'd like to try it out.

Tom

**Comment by dcwarwick** [comment]
Tom, that sounds cool. I can see the code -- props for making the src-replacement reversible rather than reloading the page. Don't forget to update the version shown in the options page to match the manifest :-)  Tried to give it a test run, but although I've loaded it as an unpacked extension I don't see the menu options for some reason - and I can't figure out why because I can see that the code in setmakamenu.js is running just fine :-/

**Comment by tresrottn** [comment]
I like that idea, Tom. It's perfect. I have a few other extensions with this very option and it's really nice. Thank you for all your hard work on this. I'm fairly code illiterate, (ok, completely illiterate) I wish I could help out!

**Comment by tomroyal** [comment]
Hi all - this option is now deployed in version 1.1.3, out now. Thanks again!

**Comment by tresrottn** [comment]
Tom, it's brilliant and works perfectly!
Thank you so very much! I love the little :( at the end :D
